### PR TITLE
Reduced return statements

### PR DESCRIPTION
**Pull request by Braunson**
As per issue #20 and https://codeclimate.com/github/Reconmap/api-backend/src/Services/Cvss.php#issue_5f787993bf6317000100008a

### CODE REVIEW

**Comment by santiagolizardo** [comment]
Thanks for your contribution @Braunson !
Unfortunately the code changes is making one of the unit tests fail: https://travis-ci.org/github/Reconmap/api-backend/builds/732539689#L2262
(this is likely due to the missing breaks between switch cases)

**Comment by Braunson** [comment]
@santiagolizardo Oh man thanks for pointing that out. Fixed.

**Review by santiagolizardo — APPROVED** [review]

**Comment by santiagolizardo** [comment]
All good now, thanks again @Braunson

**Comment by Braunson** [comment]
@santiagolizardo Mind adding the `hacktoberfest-accepted` label 😄

**Pull request merged**
